// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF6jiSz-LvutPniJtfxz4a8bPqiqAlYNM',
    appId: '1:829865279891:web:8c8151e2fcebe932062866',
    messagingSenderId: '829865279891',
    projectId: 'login-use-apple-github-twitter',
    authDomain: 'login-use-apple-github-twitter.firebaseapp.com',
    storageBucket: 'login-use-apple-github-twitter.appspot.com',
    measurementId: 'G-JN4TCJ32NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUuKHjS2I5AE1uKsso5sznpkNHgo_W1yk',
    appId: '1:829865279891:android:a0c4c556f61e56fb062866',
    messagingSenderId: '829865279891',
    projectId: 'login-use-apple-github-twitter',
    storageBucket: 'login-use-apple-github-twitter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbifgyHOsHeAnBuOR8bzhyAgwLTQsItrQ',
    appId: '1:829865279891:ios:487e7dc1be69358a062866',
    messagingSenderId: '829865279891',
    projectId: 'login-use-apple-github-twitter',
    storageBucket: 'login-use-apple-github-twitter.appspot.com',
    iosBundleId: 'com.example.loginWithGithubTwitterApple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbifgyHOsHeAnBuOR8bzhyAgwLTQsItrQ',
    appId: '1:829865279891:ios:487e7dc1be69358a062866',
    messagingSenderId: '829865279891',
    projectId: 'login-use-apple-github-twitter',
    storageBucket: 'login-use-apple-github-twitter.appspot.com',
    iosBundleId: 'com.example.loginWithGithubTwitterApple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF6jiSz-LvutPniJtfxz4a8bPqiqAlYNM',
    appId: '1:829865279891:web:d28ac3b172e9fd4d062866',
    messagingSenderId: '829865279891',
    projectId: 'login-use-apple-github-twitter',
    authDomain: 'login-use-apple-github-twitter.firebaseapp.com',
    storageBucket: 'login-use-apple-github-twitter.appspot.com',
    measurementId: 'G-LPFRJ5EV8S',
  );
}
